const PDFDocument = require('pdfkit');

const generateJAF = (job, company) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50 });
            const buffers = [];

            doc.on('data', (chunk) => buffers.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(buffers)));

            // Header
            doc.fontSize(18).font('Helvetica-Bold').text('NIT WARANGAL', { align: 'center' });
            doc.fontSize(12).font('Helvetica').text('Centre for Career Planning & Development', { align: 'center' });
            doc.moveDown(0.5);
            doc.fontSize(14).font('Helvetica-Bold').text('JOB ANNOUNCEMENT FORM (JAF)', { align: 'center' });
            doc.moveDown(1);

            // Horizontal line
            doc.strokeColor('#1a237e').lineWidth(2)
                .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
            doc.moveDown(1);

            // Company Info
            doc.fontSize(12).font('Helvetica-Bold').text('1. COMPANY DETAILS');
            doc.moveDown(0.3);
            doc.font('Helvetica').fontSize(10);
            doc.text(`Company Name: ${company.companyProfile?.companyName || 'N/A'}`);
            doc.text(`Website: ${company.companyProfile?.website || 'N/A'}`);
            doc.text(`Industry: ${company.companyProfile?.industry || 'N/A'}`);
            doc.text(`Headquarters: ${company.companyProfile?.headquarters || 'N/A'}`);
            doc.text(`Company Size: ${company.companyProfile?.companySize || 'N/A'}`);
            doc.text(`HR Contact: ${company.companyProfile?.hrName || 'N/A'} | ${company.companyProfile?.hrPhone || 'N/A'}`);
            doc.moveDown(1);

            // Job Info
            doc.fontSize(12).font('Helvetica-Bold').text('2. JOB DETAILS');
            doc.moveDown(0.3);
            doc.font('Helvetica').fontSize(10);
            doc.text(`Title: ${job.title}`);
            doc.text(`Type: ${job.jobType}`);
            doc.text(`Location: ${job.location || 'N/A'}`);
            doc.text(`Package: ${job.packageLPA?.min || 0} - ${job.packageLPA?.max || job.packageLPA?.min || 0} LPA`);
            if (job.stipend) doc.text(`Stipend: ₹${job.stipend}/month`);
            doc.text(`Deadline: ${new Date(job.deadline).toLocaleDateString('en-IN')}`);
            doc.moveDown(0.5);
            doc.text(`Description: ${job.description}`);
            doc.moveDown(1);

            // Eligibility
            doc.fontSize(12).font('Helvetica-Bold').text('3. ELIGIBILITY CRITERIA');
            doc.moveDown(0.3);
            doc.font('Helvetica').fontSize(10);
            doc.text(`Branches: ${job.eligibility?.branches?.join(', ') || 'All'}`);
            doc.text(`Minimum CGPA: ${job.eligibility?.minCGPA || 'No restriction'}`);
            doc.text(`Max Backlogs: ${job.eligibility?.maxBacklogs ?? 'No restriction'}`);
            doc.text(`Degrees: ${job.eligibility?.degrees?.join(', ') || 'All'}`);
            doc.text(`Passing Years: ${job.eligibility?.passingYears?.join(', ') || 'All'}`);
            doc.moveDown(1);

            // Skills
            if (job.skills && job.skills.length > 0) {
                doc.fontSize(12).font('Helvetica-Bold').text('4. REQUIRED SKILLS');
                doc.moveDown(0.3);
                doc.font('Helvetica').fontSize(10);
                doc.text(job.skills.join(', '));
                doc.moveDown(1);
            }

            // Footer
            doc.moveDown(2);
            doc.strokeColor('#1a237e').lineWidth(1)
                .moveTo(50, doc.y).lineTo(545, doc.y).stroke();
            doc.moveDown(0.5);
            doc.fontSize(8).fillColor('#666')
                .text('Generated by NITW Placement Portal | Confidential', { align: 'center' });

            doc.end();
        } catch (err) {
            reject(err);
        }
    });
};

module.exports = generateJAF;
